# NumPy and PyTorch

## NumPy

🧠 What is NumPy?

**NumPy** (short for Numerical Python) is a powerful Python library used for:

- Fast numerical computations.

- Working with large arrays and matrices.

- Vectorized operations (faster than Python loops).

🛠️ Installing NumPy
If you're using pip, you can install NumPy like this:
```bash
pip install numpy
```

If you're in a Jupyter Notebook:
```python
!pip install numpy
```

✅ Why Use NumPy Instead of Lists? 

- Cleaner.

- Faster.

- More efficient for large data.

### 🔢 Creating arrays in NumPy

In [1]:
import numpy as np

# 1. Creating arrays from lists
arr1 = np.array([1, 2, 3, 4])                  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])        # 2D array

# 2. Predefined arrays
zeros = np.zeros((2, 3))                      # 2x3 array of zeros
ones = np.ones((2, 3))                        # 2x3 array of ones
full = np.full((2, 2), 7)                     # 2x2 array filled with 7s
empty = np.empty((2, 2))                      # 2x2 array with uninitialized values

# 3. Ranges and sequences
ar = np.arange(0, 10, 2)                      # Array from 0 to 8, step 2
lin = np.linspace(0, 1, 5)                    # 5 values evenly spaced from 0 to 1

# 4. Identity matrix
identity = np.eye(3)                         # 3x3 identity matrix

# 5. Print all arrays with clear formatting
print("=== 1. Arrays from Lists ===")
print("1D array:", arr1)
print("2D array:\n", arr2)

print("\n=== 2. Predefined Arrays ===")
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Full (7s):\n", full)
print("Empty (uninitialized):\n", empty)

print("\n=== 3. Sequences ===")
print("Arange:", ar)
print("Linspace:", lin)

print("\n=== 4. Identity Matrix ===")
print(identity)

=== 1. Arrays from Lists ===
1D array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]

=== 2. Predefined Arrays ===
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full (7s):
 [[7 7]
 [7 7]]
Empty (uninitialized):
 [[0. 0.]
 [0. 0.]]

=== 3. Sequences ===
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]

=== 4. Identity Matrix ===
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import sys
print(sys.executable)


/Users/richardzhang/miniconda3/bin/python


### 🔍 Array Attributes

In [2]:
import numpy as np

# Create some sample arrays
a = np.array([10, 20, 30])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[[1], [2]], [[3], [4]]])  # 3D array

# Print array attributes
print("=== 1. Array 'a' (1D) ===")
print("Array:", a)
print("Dimensions (ndim):", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Data type (dtype):", a.dtype)

print("\n=== 2. Array 'b' (2D) ===")
print("Array:\n", b)
print("Dimensions:", b.ndim)
print("Shape:", b.shape)
print("Size:", b.size)
print("Dtype:", b.dtype)

print("\n=== 3. Array 'c' (3D) ===")
print("Array:\n", c)
print("Dimensions:", c.ndim)
print("Shape:", c.shape)
print("Size:", c.size)
print("Dtype:", c.dtype)


=== 1. Array 'a' (1D) ===
Array: [10 20 30]
Dimensions (ndim): 1
Shape: (3,)
Size: 3
Data type (dtype): int64

=== 2. Array 'b' (2D) ===
Array:
 [[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Size: 6
Dtype: int64

=== 3. Array 'c' (3D) ===
Array:
 [[[1]
  [2]]

 [[3]
  [4]]]
Dimensions: 3
Shape: (2, 2, 1)
Size: 4
Dtype: int64


### ✂️ Indexing and Slicing

In [3]:
import numpy as np

# Sample arrays
a = np.array([10, 20, 30, 40, 50])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1D Indexing and Slicing
print("a[0]:", a[0])           # First element
print("a[-1]:", a[-1])         # Last element
print("a[1:4]:", a[1:4])       # Slice
print("a[::2]:", a[::2])       # Every other element

# 2D Indexing and Slicing
print("b[0, 1]:", b[0, 1])          # Specific element
print("b[:, 0]:", b[:, 0])          # First column
print("b[0, :]:", b[0, :])          # First row
print("b[:2, :2]:\n", b[:2, :2])    # 2x2 top-left

# Fancy Indexing
print("b[[0, 2], [1, 2]]:", b[[0, 2], [1, 2]])  # b[0,1] and b[2,2]

# Boolean Masking
print("a[a > 25]:", a[a > 25])  # Filtered values


a[0]: 10
a[-1]: 50
a[1:4]: [20 30 40]
a[::2]: [10 30 50]
b[0, 1]: 2
b[:, 0]: [1 4 7]
b[0, :]: [1 2 3]
b[:2, :2]:
 [[1 2]
 [4 5]]
b[[0, 2], [1, 2]]: [2 9]
a[a > 25]: [30 40 50]


### 🧮 Array operations

In [4]:
import numpy as np

# Arrays for operation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise arithmetic
print("a + b:", a + b)
print("a * b:", a * b)
print("a ** 2:", a ** 2)

# Comparison and logic
print("a > 1:", a > 1)
print("(a > 1) & (b < 6):", (a > 1) & (b < 6))

# Aggregate functions
print("sum of a:", np.sum(a))
print("mean of b:", np.mean(b))
print("max of a:", np.max(a))


a + b: [5 7 9]
a * b: [ 4 10 18]
a ** 2: [1 4 9]
a > 1: [False  True  True]
(a > 1) & (b < 6): [False  True False]
sum of a: 6
mean of b: 5.0
max of a: 3


### 🔁 Reshaping and Resizing

In [5]:
import numpy as np

# Original array
a = np.arange(1, 7)  # [1 2 3 4 5 6]

# Reshaping
reshaped = a.reshape((2, 3))      # 2 rows, 3 columns
flattened = reshaped.ravel()      # Flattens without copy
copied_flat = reshaped.flatten()  # Flattens with copy

# Transposing
transposed = reshaped.T         # Swaps rows and columns

# Expanding dimensions
row_vec = a[np.newaxis, :]      # From 1D to 2D row
col_vec = a[:, np.newaxis]      # From 1D to 2D column

# Print results
print("Original:", a)
print("Reshaped (2x3):\n", reshaped)
print("Flattened (view):", flattened)
print("Flattened (copy):", copied_flat)
print("Transposed:\n", transposed)
print("Row vector shape:", row_vec.shape)
print("Column vector shape:", col_vec.shape)


Original: [1 2 3 4 5 6]
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
Flattened (view): [1 2 3 4 5 6]
Flattened (copy): [1 2 3 4 5 6]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]
Row vector shape: (1, 6)
Column vector shape: (6, 1)


### 📐 Mathematical functions

In [6]:
import numpy as np

# Sample data
a = np.array([1, 2, 3, 4])
b = np.array([0.1, 0.2, 0.3, 0.4])

# Element-wise math functions
print("Square root:", np.sqrt(a))
print("Exponential:", np.exp(a))
print("Natural log:", np.log(a))

# Trigonometric functions (in radians)
print("Sine:", np.sin(b))
print("Cosine:", np.cos(b))
print("Tangent:", np.tan(b))

# Matrix multiplication
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Matrix product:\n", np.dot(m1, m2))  # or m1 @ m2


Square root: [1.         1.41421356 1.73205081 2.        ]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Natural log: [0.         0.69314718 1.09861229 1.38629436]
Sine: [0.09983342 0.19866933 0.29552021 0.38941834]
Cosine: [0.99500417 0.98006658 0.95533649 0.92106099]
Tangent: [0.10033467 0.20271004 0.30933625 0.42279322]
Matrix product:
 [[19 22]
 [43 50]]


### 🎭 Filtering and Masking

In [7]:
import numpy as np

# Sample array
data = np.array([12, 7, 5, 19, 3, 14, 8])

# Basic filtering
greater_than_10 = data[data > 10]                  # values > 10

# Combining conditions
between_5_and_15 = data[(data >= 5) & (data <= 15)]
outside_range = data[(data < 5) | (data > 15)]

# Using np.where to get indices
indices = np.where(data > 10)                      # positions of values > 10

# Using np.where to replace values
replaced = np.where(data > 10, -1, data)          # replace with -1 if > 10, else keep

# Print outputs
print("Original:", data)
print("Values > 10:", greater_than_10)
print("Between 5 and 15:", between_5_and_15)
print("Outside 5–15:", outside_range)
print("Indices of values > 10:", indices)
print("Replace >10 with 100:", replaced)


Original: [12  7  5 19  3 14  8]
Values > 10: [12 19 14]
Between 5 and 15: [12  7  5 14  8]
Outside 5–15: [19  3]
Indices of values > 10: (array([0, 3, 5]),)
Replace >10 with 100: [-1  7  5 -1  3 -1  8]


### 🎲 Random Module

In [8]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# 1. Random values
rand_uniform = np.random.rand(3, 2)         # Uniform [0, 1), shape (3, 2)
rand_normal = np.random.randn(4)            # Standard normal distribution (mean=0, std=1)
rand_ints = np.random.randint(1, 10, size=5)  # 5 integers from [1, 10)

# 2. Random choice
cities = ["Copenhagen", "Aarhus", "Odense", "Aalborg"]
sample = np.random.choice(cities, size=3, replace=False)  # sample without replacement

# 3. Shuffle and permutation
numbers = np.arange(1, 6)
shuffled = numbers.copy()
np.random.shuffle(shuffled)                 # In-place shuffle

permuted = np.random.permutation(numbers)   # Returns a new shuffled array

# Print results
print("Random uniform (3x2):\n", rand_uniform)
print("Random normal (4):", rand_normal)
print("Random integers:", rand_ints)
print("Random city sample:", sample)
print("Shuffled (in-place):", shuffled)
print("Permuted (new array):", permuted)


Random uniform (3x2):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
Random normal (4): [ 1.57921282  0.76743473 -0.46947439  0.54256004]
Random integers: [5 1 6 9 1]
Random city sample: ['Aarhus' 'Copenhagen' 'Aalborg']
Shuffled (in-place): [1 5 3 4 2]
Permuted (new array): [1 2 5 4 3]


### ⚠️ Common Pitfalls

In [9]:
import numpy as np

# 1. Mixing Python lists and NumPy arrays
arr = np.array([1, 2, 3])
bad_sum = arr + [4, 5, 6]      # Works, but might be confusing: adds element-wise, not concatenates
print("Element-wise sum with list:", bad_sum)

# 2. Copy vs view (modifying unintended data)
original = np.array([1, 2, 3])
view = original[1:]            # This is a view (not a copy)
view[0] = 99                   # Also changes original!
print("Original after view-modified:", original)

# To avoid: use .copy()
safe = original.copy()
safe[0] = 100
print("Original after safe copy:", original)

# 3. Shape mismatch in operations
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])
try:
    result = a + b             # Works: broadcasting
    print("Broadcasted sum:\n", result)
    
    c = np.array([1, 2])
    result_fail = a + c        # Fails: shapes incompatible
except ValueError as e:
    print("Shape mismatch error:", e)


Element-wise sum with list: [5 7 9]
Original after view-modified: [ 1 99  3]
Original after safe copy: [ 1 99  3]
Broadcasted sum:
 [[2 4 6]
 [5 7 9]]
Shape mismatch error: operands could not be broadcast together with shapes (3,) (2,) 


## PyTorch

🧠 What is PyTorch?

**PyTorch** is an open-source deep learning library developed by Meta (formerly Facebook). It’s popular for:

- Building and training neural networks  
- Fast, flexible tensor computations (like NumPy with GPU support)  
- Automatic differentiation for optimization (via autograd)

🛠️ Installing PyTorch

Use the official install command generator:  
👉 https://pytorch.org/get-started/locally/

Or, for most basic setups (CPU-only):

```bash
pip install torch
```

✅ Why Use PyTorch?
- Dynamic computation graphs (define-as-you-run)

- Built-in GPU support

- Friendly syntax similar to NumPy

- Industry-standard for deep learning research and production

### 🔥 Introduction to PyTorch

In [ ]:
import torch

# Create a simple tensor
x = torch.tensor([1.0, 2.0, 3.0])  # 1D float tensor
print("Tensor x:", x)

# Check tensor attributes
print("Shape:", x.shape)
print("Data type:", x.dtype)
print("Device:", x.device)

# Create a tensor with requires_grad (for autograd later)
x_grad = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print("Requires grad:", x_grad.requires_grad)

# Check for GPU support and move a tensor to CUDA if available
if torch.cuda.is_available():
    x_cuda = x.to("cuda")
    print("Tensor on GPU:", x_cuda)
else:
    print("CUDA not available — running on CPU")


### 🔢 Creating Tensors in PyTorch

In [ ]:
import torch
import numpy as np

# 1. From Python lists
a = torch.tensor([1, 2, 3])                  # 1D tensor
b = torch.tensor([[1, 2], [3, 4]])           # 2D tensor

# 2. With default values
zeros = torch.zeros((2, 3))                 # 2x3 tensor of zeros
ones = torch.ones((2, 3))                   # 2x3 tensor of ones
rand = torch.rand((2, 2))                   # Uniform [0, 1)
randn = torch.randn((2, 2))                 # Normal distribution
arange = torch.arange(0, 10, 2)             # Like Python range
eye = torch.eye(3)                          # Identity matrix

# 3. Specifying dtype
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
int_tensor = torch.tensor([1.5, 2.5, 3.5], dtype=torch.int32)

# 4. From NumPy array
np_arr = np.array([[1, 2], [3, 4]])
t_from_np = torch.tensor(np_arr, dtype=torch.int32)

# Print a few key results
print("a:", a)
print("zeros:\n", zeros)
print("rand:\n", rand)
print("arange:", arange)
print("from numpy:\n", t_from_np)
print("float tensor:", float_tensor)
print("int tensor (truncated):", int_tensor)


### 🔍 Tensor Attributes

In [ ]:
import torch

# Sample tensors
x = torch.randn((2, 3))
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

# Inspect attributes
print("x:\n", x)
print("x.shape:", x.shape)
print("x.ndim:", x.ndim)
print("x.dtype:", x.dtype)
print("x.device:", x.device)
print("x.requires_grad:", x.requires_grad)

print("\ny:\n", y)
print("y.shape:", y.shape)
print("y.dtype:", y.dtype)
print("y.numel():", y.numel())  # Total number of elements


### ✂️ Indexing, Slicing, and Masking

In [ ]:
import torch

# Sample tensors
a = torch.tensor([10, 20, 30, 40, 50])
b = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 1D indexing & slicing
print("a[0]:", a[0])              # First element
print("a[-1]:", a[-1])            # Last element
print("a[1:4]:", a[1:4])          # Slice
print("a[::2]:", a[::2])          # Every other element

# 2D indexing
print("b[1, 2]:", b[1, 2])        # Row 1, col 2
print("b[:, 0]:", b[:, 0])        # First column
print("b[0, :]:", b[0, :])        # First row
print("b[1:, 1:]:\n", b[1:, 1:])  # Bottom-right submatrix

# Boolean masking
mask = a > 25
print("Mask:", mask)
print("a[mask]:", a[mask])        # Values where a > 25

# In-place modification
a[a > 30] = -1
print("Modified a:", a)

### 🧮 Tensor Operations

In [ ]:
import torch

# Sample tensors
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

# Arithmetic operations
print("a + b:", a + b)
print("a * b:", a * b)
print("a ** 2:", a ** 2)

# Comparison operations
print("a > 2:", a > 2)

# Aggregation / reductions
print("sum(a):", torch.sum(a))
print("mean(b):", torch.mean(b))
print("max(a):", torch.max(a))
print("argmax(b):", torch.argmax(b))  # Index of max value

# Broadcasting example
c = torch.tensor([[1.0], [2.0], [3.0]])  # Shape (3, 1)
d = torch.tensor([10.0, 20.0])           # Shape (2,)
print("Broadcasted c * d:\n", c * d)     # Shape (3, 2)


### 🔁 Reshaping and Views

In [ ]:
import torch

# Create a tensor
x = torch.arange(1, 7)           # [1, 2, 3, 4, 5, 6]

# Reshape to 2x3
reshaped = x.view(2, 3)          # Same as .reshape()
print("Reshaped (2x3):\n", reshaped)

# Flattening
flat = reshaped.view(-1)         # Collapse to 1D
print("Flattened:", flat)

# Adding dimensions
row_vec = x.unsqueeze(0)         # Shape: (1, 6)
col_vec = x.unsqueeze(1)         # Shape: (6, 1)
print("Row vector shape:", row_vec.shape)
print("Col vector shape:", col_vec.shape)

# Removing dimensions
squeezed = col_vec.squeeze()     # Removes all dims of size 1
print("Squeezed shape:", squeezed.shape)

# Transposing a matrix
m = torch.tensor([[1, 2], [3, 4]])
print("Transposed:\n", m.T)


### 🧠 Autograd (Automatic Differentiation)

In [ ]:
import torch

# 1. Create a tensor with gradient tracking
x = torch.tensor([2.0], requires_grad=True)

# 2. Define a simple function: y = x² + 3x
y = x**2 + 3 * x

# 3. Backpropagate to compute dy/dx (More on this in the upcoming weeks)
y.backward()

# 4. Access the gradient
print("x:", x.item())
print("y:", y.item())
print("dy/dx:", x.grad.item())  # Should be 2x + 3 → 2*2 + 3 = 7

# 5. Resetting gradient (common in training loops)
x.grad.zero_()

# Optional: compute multiple steps
a = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
z = (a * a).sum()     # z = a₁² + a₂² + a₃²
z.backward()
print("Gradient of z w.r.t a:", a.grad)  # dz/da = 2a
